name: Deploy PHP Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo, json

      # Step 3: Debug the file structure
      - name: List files for debugging
        run: ls -R

      # Step 4: Install Composer dependencies
      - name: Install PHP dependencies
        run: composer install
        working-directory: ./test-composer/test-composer/

      # Step 5: Deploy to server
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            debug: true
            script: |
                cd /var/www/html
                git pull origin main
                php artisan migrate --force
        